// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return web;

        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return web;
      // throw UnsupportedError(
      //   'DefaultFirebaseOptions have not been configured for windows - '
      //   'you can reconfigure this by running the FlutterFire CLI again.',
      // );
      case TargetPlatform.linux:
        return web;

        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZSHzjzdh1A8J_Ini5CEA0GIwJh0MOmjQ',
    appId: '1:808637490319:android:71a7daa29516439b7cbcfa',
    messagingSenderId: '808637490319',
    projectId: 'frontendbooakdngo3',
    storageBucket: 'frontendbooakdngo3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCJDvBaX9K0LOMpcHri0miwk5Q5rZ4tCY',
    appId: '1:808637490319:ios:a856dad0685886bf7cbcfa',
    messagingSenderId: '808637490319',
    projectId: 'frontendbooakdngo3',
    storageBucket: 'frontendbooakdngo3.firebasestorage.app',
    iosBundleId: 'com.rivierapadel.bookandgo',
  );

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyAkIvYpZS9hdLWgImL9oJexB8ehix4cErk",
      authDomain: "jungle-padel-327a6.firebaseapp.com",
      projectId: "jungle-padel-327a6",
      storageBucket: "jungle-padel-327a6.appspot.com",
      messagingSenderId: "1017484623328",
      appId: "1:1017484623328:web:a6a2d71f35e3cb5edbff85",
      measurementId: "G-Y2QB08YL7V");
}