default_platform(:android)

platform :android do

  desc "Deploy pre-built AAB to Google Play (production)"
  lane :deploy do
    upload_to_play_store(
      json_key_data: ENV["PLAY_STORE_JSON_KEY"],
      aab: "../build/app/outputs/bundle/release/app-release.aab",
      track: "production",
      skip_upload_metadata: true,
      skip_upload_changelogs: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end

  desc "Deploy pre-built AAB to Google Play (internal testing)"
  lane :internal do
    upload_to_play_store(
      json_key_data: ENV["PLAY_STORE_JSON_KEY"],
      aab: "../build/app/outputs/bundle/release/app-release.aab",
      track: "internal",
      skip_upload_metadata: true,
      skip_upload_changelogs: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end

end
